  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Research"
  weight = 200
  identifier = "research"
  url = "/research/"

  [[main]]
  name = "Publications"
  weight = 300
  identifier = "publications"
  url = "/publications/"

  [[main]]
  name = "Talks"
  weight = 400
  identifier = "talks"
  url = "/talks/"

  [[main]]
  name = "Teaching"
  weight = 510
  identifier = "teaching"
  url = "/teaching/"
